In [39]:
import pandas as pd
import numpy as np

# 1 Question
     A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between twounits.
    A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and 
    draw inferences at 5% significance level. 
    Please state the assumptions and tests that you carried out to check validity of the assumptions.


# step 1 : importing  the CSV File

In [ ]:
d1 = pd.read_csv("Cutlets.csv")
d1

In [ ]:
#Let Us assume the the NULL HYpotheses(H0) and ALTERNATIVE Hypotheses(H1)

In [ ]:
H0 : unitA == unitB
H1 : unitA != unitb

In [ ]:
#from the above question we have to use the Two sample Z test

In [ ]:
from scipy import stats

In [ ]:
#Calcualte the Zcal,Pvalues

In [ ]:
Zcal,pvalue = stats.ttest_ind(d1['Unit A'],d1['Unit B'])
print("Z calculated value is",Zcal.round(3))
print("p value is",pvalue.round(3))

In [ ]:
if pvalue<0.05:
    print("H0 is rejected and H1 is accepted")
else:
    print("H1 is rejected and H0 is accepted")

In [ ]:
#conclusion : there is no significant difference in the diameter of the cutlet between two units,

# 2Question

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level


In [3]:
d2 = pd.read_csv("LabTAT.csv")
d2

<IPython.core.display.Javascript object>

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [ ]:
#checking the means for the laboratories

In [8]:
L1 = d2['Laboratory 1'].mean()
L1

178.36158333333339

In [9]:
L2 = d2['Laboratory 2'].mean()
L2

178.9029166666668

In [10]:
L3 = d2['Laboratory 3'].mean()
L3

199.91325000000003

In [11]:
L4 = d2['Laboratory 4'].mean()
L4

163.6827499999999

In [ ]:
#From the above obsevation the mean of laboratories are different
#So we have to use the ANOVA Test

In [ ]:
#HO : L1 = L2 = L3 = L4
#H1 : L1 !=L2.........

In [34]:
statistic, p_value = stats.f_oneway(d2["Laboratory 1"],d2["Laboratory 2"],d2["Laboratory 3"],d2["Laboratory 4"])


<IPython.core.display.Javascript object>

In [35]:
statistic

118.70421654401437

In [36]:
p_value


2.1156708949992414e-57

In [40]:
if p_value<0.05:
    print("H0 is rejected and H1 is accepted")
else:
    print("H1 is rejected and H0 is accepted")

H0 is rejected and H1 is accepted


In [ ]:
#HO : L1 = L2 = L3 = L4
#H1 : L1 !=L2.........(different) is accepted

In [ ]:
#Conclsion : As we can say that there is a difference in avearge TAT among the different laborartories

# 3question


In [ ]:
#importing the CSV file

In [41]:
d3 = pd.read_csv("BuyerRatio.csv")
d3

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
#lets us assume the H0 and H1
H0 : All proportions are equal
H1 : Not all proportins are equal

In [ ]:
#so that we have to use the  chi_square test

In [43]:
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [56]:
# Make dimensional array
table =np.array([[50,142,131,70],[435,1523,1356,750]])
table

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [57]:
# Chi2 contengency independence test
output =chi2_contingency(table)
output

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [49]:
# o/p is (Chi2 stats value, p_value, df, expected observation)

In [54]:
pvalues = 0.66030949

In [58]:

#conclusion : H1 : All proportions are not equal

# 4question
     TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [59]:
d4 = pd.read_csv("Costomer+OrderForm.csv")
d4

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [ ]:
#let us assume that 
H0: Phillippines=Indonesia=Malta=India
H1: different

In [60]:
d4.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [61]:
d4.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [62]:
d4.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [63]:
d4.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [ ]:
#we have to put them in a table by using array operation using numpy

In [64]:
import numpy as np

In [65]:
# Make a contingency table
table=np.array([[271,267,269,280],[29,33,31,20]])
table

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [66]:
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [67]:
chi2_contingency(table)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [69]:
pvalues = 0.277102099

In [72]:
if pvalues == 0.05:
    print("H0 is rejected and H1 is accepted")
else:
    print("H1 is rejected and H0 is accepted")

H1 is rejected and H0 is accepted


In [ ]:
#null hypothesis is accepted(H0)